# 证件类型配置模板
id_card:
  name: 身份证
  fields:
    - name: 姓名
      region: [100, 50, 300, 100]  # 坐标范围 (x1,y1,x2,y2)
      regex: "^[\u4e00-\u9fa5]{2,4}$"  # 2-4个汉字
    - name: 身份证号
      regex: "^[1-9]\d{16}[\dXx]$"
driver_license:
  name: 驾驶证
  fields:
    - name: 姓名
      region: [80, 60, 250, 120]
      regex: "^[\u4e00-\u9fa5]{2,4}$"
    - name: 证号
      regex: "^\d{12}$"
social_security_card:
  name: 社保卡
  fields:
    - name: 社保号
      regex: "^\d{9}$"